stages:
    train:
        cmd: PYTHONPATH=. python scripts/training/run_train_multitask_experiment.py
        params:
            - train.method
            - train.datasets
            - train.loss_func
            - train.model
            - train.num_repeats
            - train.model_random_state
            - train.data_random_state
            - train.num_workers
            - train.gpus
            - train.max_steps
            - train.warmup_steps_ratio
            - train.batch_size
            - train.accumulate_grad_batches
            - train.learning_rate
            - train.max_length
            - train.gradient_checkpointing
            - train.freeze_backbone
            - linear.learning_rate
            - linear.batch_size
            - linear.gradient_checkpointing
            - linear.freeze_backbone
        metrics:
          - data/metrics/metrics.json:
              cache: false